Jazzy as latest
open-rmf/rmf-web pull request #1020
Opened 2024-10-23 08:03 UTC by aaronchongth

## What's new

* tagging `jazzy` as `latest` as well

## Self-checks

- [ ] I have prototyped this new feature (if necessary) on Figma 
- [ ] I'm familiar with and follow this [Typescript guideline](https://basarat.gitbook.io/typescript/styleguide)
- [ ] I added unit-tests for new components
- [ ] I tried testing edge cases
- [ ] I tested the behavior of the components that interact with the backend, with an e2e test

2024-10-23 19:08 UTC, koonpeng approved these changes

2024-10-23 19:17 UTC, koonpeng requested changes

2024-10-23 19:17 UTC, koonpeng commented on .github/workflows/nightly.yml
> +            ${{ matrix.ros_distribution == 'jazzy' && format('ghcr.io/{0}/api-server:latest', github.repository) || null}}
I just realized that this is a nightly ci, so we should tag them as `jazzy-nightly` and `rolling-nightly` instead. `jazzy` and `rolling` should point to the latest released version.

2024-10-29 11:06 UTC, aaronchongth commented
Good point, I've opened https://github.com/open-rmf/rmf-web/issues/1022 to as a reminder to set up that workflow to be triggered by releases

2024-11-04 02:40 UTC, koonpeng approved these changes

2024-11-04 10:50 UTC, aaronchongth commented
Will merge this after https://github.com/open-rmf/rmf-web/pull/1007, since conflicts will only be in 2 files

2024-11-07 03:59 UTC, merged