dashboard: add react-mosaic-component and minimal route
open-rmf/rmf-web pull request #262
Opened 2021-03-12 07:29 UTC by codebot

## What's new

This feature adds the `react-mosaic-component` package (and some dependencies), as well as a minimal working example on the `/mosaic` route which shows the building map in a panel, as well as two placeholder panels that can be resized and moved around.

At first I had a few more placeholder panels that had sample data, but I thought it would be easier for review small PR's, so this first one is just the "layout manager framework" PR. We can create panels one-by-one in additional PR's once we iterate on this enough to get it in.

## Self-checks

- [ ] I'm familiar with and follow this [Typescript guideline](https://basarat.gitbook.io/typescript/styleguide)
- [ ] I added unit-tests for new components
- [X] I tried testing edge cases
- [X] I tested the behavior of the components that interact with the backend, with an e2e test

2021-03-12 21:08 UTC, matiasbavera reviewed
Looking good! Left a couple of comments 

HTH,

2021-03-13 12:40 UTC, koonpeng requested changes
It would be really helpful to add some tests as well.

2021-03-13 12:40 UTC, koonpeng commented on packages/dashboard/package.json
> +    "@blueprintjs/icons": "^3.25.1",
I agree, mixing frameworks usually lead to bloat and inconsistent user experience.

2021-03-13 12:40 UTC, koonpeng commented on packages/dashboard/src/components/app.tsx
> +                        <PrivateRoute exact path={MOSAIC_ROUTE}>
I would prefer to remove this route until there is a usable UI, on a side note, is the goal of this to provide several pre-arranged layouts each in its own route, or is it to provide a single route that the user can customize "free-style" to their liking?

2021-03-13 12:40 UTC, koonpeng commented on packages/dashboard/src/components/layout-manager/layout-manager.tsx
> +import './layout-manager.css';
+1, I prefer to keep css-in-js, it is also probably needed to make the theming consistent.

2021-03-13 12:40 UTC, koonpeng commented on packages/dashboard/src/components/layout-manager/layout-manager.tsx
> +export default function LayoutManager(_props: {}): React.ReactElement {
I'm not familiar with mosaic but it seems like the layout in this component is fixed? I would think `LayoutManager` would be something that works with different layouts.

2021-03-15 18:12 UTC, matiasbavera commented on packages/dashboard/package.json
> +    "@blueprintjs/icons": "^3.25.1",
> From reading issue logs on `react-mosaic`, It seems this is a known warning, without an easy solution. I guess we could fork `react-mosaic` and hack out all references to `blueprintjs`. I think that is what they did for `webviz`.

Yeah, it looks like there isn't an easy fast way to do it. This is the issue that react-mosaic puts about the warning https://github.com/nomcopter/react-mosaic/issues/109 on webpack. 

Fork the repo or put it directly on rmf-web both seem like viable options.

The benefit of forking the repo is that it'll be "easier" to update the project if the main repo releases a new version. 

> But I suppose we could also just fork the repo into the open-rmf org, but then (at least in my mind) getting the build set up seems more difficult, especially if we're going to be doing a decent amount of tweaking to react-mosaic.

You mean to use it in the `rmf-web/dashboard` right? That repo has its `build/bundle` configuration already set up. 

I think (and KP will correct me if I'm wrong) we can add that fork into `open-rmf` and use it in `rmf-web` as a git submodule.

I dug a bit in the source code I think they are just using that troublemaker component https://github.com/nomcopter/react-mosaic/blob/master/src/util/OptionalBlueprint.tsx for style class extension. 

![image](https://user-images.githubusercontent.com/11761240/111200138-2cee2c00-85a0-11eb-8814-034b9e9ae39b.png)


----------------------------------------------------------

I need to ask this question before we continue, can we leave this "problem" as a technical debt just until we decide 100% to keep this library (sorry if I'm outdated and we already decided that =) ). I mean after you complete testing all the features we need.

2021-03-15 18:39 UTC, matiasbavera commented on packages/dashboard/src/components/app.tsx
> +                        <PrivateRoute exact path={MOSAIC_ROUTE}>
Mmh.. maybe with the storybook but you'd not be able to put the schedule-visualizer

2021-03-16 01:14 UTC, koonpeng commented on packages/dashboard/src/components/layout-manager/layout-manager.tsx
> +export default function LayoutManager(_props: {}): React.ReactElement {
What confuses me is this line
```tsx
if (id === 'map_2d') return <BuildingMapWindow path={path} />;
```
it seems hardcoded to return a `BuildingMapWindow` or a `div`. It's not clear to me how to use this component with different windows/panels. I thought following react pattern, it should take in some props and childrens to control what windows are rendered.

2021-03-16 01:34 UTC, koonpeng commented on packages/dashboard/package.json
> +    "@blueprintjs/icons": "^3.25.1",
Other than removing blueprint, we should also look at using material for theming.

As mentioned, forking has the advantage of easier upstream sync, and maybe better organization as we avoid making `rmf-web` get too cluttered, I think we should avoid a similar problem we had in `rmf_core` and other old rmf repos (becoming too cluttered and now being re-organized). Absorbing into `rmf-web` has the advantage of easier development as we can use it as local dependencies.

I think if there is plans to share a version of `react-mosaic` that uses material for styling, forking is the better approach. Although there isn't any release mechanisms in this repo yet, but being a monorepo, pulling `react-mosaic` in here would require us to version it together with all other packages in this repo.

Note: In an ideal scenario, development of the fork should not impact `rmf-web`, but you can use `npm link` to use a local dev version of a package to test the new `react-mosaic` if needed.

2021-03-16 03:30 UTC, koonpeng commented on packages/dashboard/src/components/layout-manager/layout-manager.tsx
> +export default function LayoutManager(_props: {}): React.ReactElement {
In that case, I think we can show it using storybook, `LayoutManager` could be a story, and there would be no need to add a wip route to the dashboard.

2021-03-16 03:36 UTC, koonpeng commented on packages/dashboard/src/components/app.tsx
> +                        <PrivateRoute exact path={MOSAIC_ROUTE}>
It should now be possible to use `ScheduleVisualizer` with storybook, its been refactored to take in data from react contexts so you can use it as long as you provide some data to it.

2021-10-14 02:58 UTC, closed without merging