react-components: robot panel
open-rmf/rmf-web pull request #335
Opened 2021-05-17 01:06 UTC by vallq

## What's new
Robot Panel component based off from Task Panel
![robot panel ui](https://user-images.githubusercontent.com/28668944/118419129-bd0a3800-b6ed-11eb-8946-eef61093b1dc.png)
- will be removing the refresh button

## Self-checks

- [x] I'm familiar with and follow this [Typescript guideline](https://basarat.gitbook.io/typescript/styleguide)
- [x] I added unit-tests for new components
- [ ] I tried testing edge cases
- [ ] I tested the behavior of the components that interact with the backend, with an e2e test

## Discussion
1. I'm still not sure how to use the `api_server`'s implementation of task progress in `react-components` because what react-components use is technically just dummy data. should this be taken as a prop and only implemented in the dashboard?

2. The original idea was to also have 'Est End Time' be a clock value in 12hour format, and likewise, I'm not sure how this can be done. using `rosTimeToJs` in `lib/utils.ts`?

2021-05-19 20:10 UTC, matiasbavera requested changes
Hi Val, left a couple of comments, HTH

2021-05-19 20:10 UTC, matiasbavera commented on packages/react-components/lib/robots/robot-panel.tsx
> +          {selectedRobot ? <RobotInfo robot={selectedRobot} /> : <NoSelectedRobot />}
Does it improve the performance if you store this on a `React.useMemo` or using `React.memo` on `RobotInfo ` component?

2021-05-20 09:01 UTC, koonpeng reviewed
I'm going to push some changes to this branch that adds some features to make query the tasks/robots easier.

When using the new task query api, you can pass the list of tasks as an object, you can get the task_id with RobotState.task_id. On the dashboard side you can

1. Use `/fleets` to get a list of fleets.
2. Use `/fleets/{name}/state` to get the state of each fleet (and robots), this is inefficient as it means sending a request for each fleet, but it is the best we have now.
3. Use `/tasks?task_id=a,b,c` to get the task summary of each task.

2021-05-20 09:14 UTC, koonpeng commented
from the other pr:
> oh okay!
other than the current tasks, is it possible to retrieve all assigned and active tasks? (completed/failed tasks are not needed). because there is an 'assigned tasks' section in the robot-info.tsx

oh I see, the information in robot state is not enough, I think disregard the above guide. Just use the task query api the find the list of assigned tasks for a robot. The new additions allow you to query by multiple robot/fleet/states so you should be able to get the required data.

2021-05-24 00:47 UTC, koonpeng commented on packages/react-components/lib/robots/utils.ts
> +    const assignedTasks = tasks.filter((task) => {
I think we should add a TODO to move this to the server. The server will have a robots endpoints returning the equivalent of `VerboseRobot`.

2021-05-24 00:47 UTC, koonpeng commented on packages/react-components/lib/robots/robot-table.tsx
> +  robots: RmfModels.RobotState[];
Could this take in a `VerboseRobot` instead?

2021-05-24 01:15 UTC, koonpeng commented
I realised the robots endpoints will need more work to get the required info, so I think I will revert the api-server changes and work on it on another branch.

2021-05-25 04:18 UTC, closed without merging

2021-05-25 04:19 UTC, vallq commented
updated branch: `dashboard/robot-page`