docs:reporting-server: Update reporting-server documentation
open-rmf/rmf-web pull request #408
Opened 2021-06-29 23:38 UTC by matiasbavera

Signed-off-by: Matias Bavera <matiasbavera@gmail.com>

## What's new
Added documentation on the reporting-server

## Self-checks

- [ ] I'm familiar with and follow this [Typescript guideline](https://basarat.gitbook.io/typescript/styleguide)
- [ ] I added unit-tests for new components
- [ ] I tried testing edge cases
- [ ] I tested the behavior of the components that interact with the backend, with an e2e test

## Discussion

2021-06-30 07:20 UTC, vallq requested changes
I think this line `npm run bootstrap -- packages/reporting-server` has to be updated with `lerna bootstrap --scope=reporting-server` too!

Thanks for this, @matiasbavera . I think it's a lot clearer with the diagrams and the explanation of the roles of ports 8002 and 8003.

2021-06-30 07:20 UTC, vallq commented on packages/reporting-server/README.md
> +![reporting-server](https://user-images.githubusercontent.com/11761240/123880883-9147b800-d911-11eb-88e8-f771914089ae.png)
Thanks for the diagram! I corrected a typo
```suggestion
![rmf-web kubernetes cluster diagram](https://user-images.githubusercontent.com/28668944/123916706-8b56e300-d9b4-11eb-990f-69e717f87b38.png)

```

2021-06-30 07:20 UTC, vallq commented on packages/reporting-server/README.md
> +![reporting-server](https://user-images.githubusercontent.com/11761240/123880883-9147b800-d911-11eb-88e8-f771914089ae.png)
![rmf-web kubernetes cluster diagram](https://user-images.githubusercontent.com/28668944/123916839-ac1f3880-d9b4-11eb-8231-67c93875b582.png)

2021-06-30 07:27 UTC, vallq commented
![image](https://user-images.githubusercontent.com/28668944/123919110-2b157080-d9b7-11eb-876a-357ac82a3322.png)
Oh yea I don't know if this should go here but when I run `reporting_server` in my terminal, and use CTRL+C to quit, the process lingers on the terminal.
![image](https://user-images.githubusercontent.com/28668944/123919608-ae36c680-d9b7-11eb-9b7f-c04cd64baf15.png)
I have to use `kill -9 <process id>` on another terminal. It works fine for the live reload uvicorn command.

2021-06-30 17:01 UTC, matiasbavera commented
Thanks for the comments @vallq

2021-07-01 03:35 UTC, vallq approved these changes
Thanks for updating the docs! I will merge this in. And we can make subsequent edits if other comments come up.

2021-07-01 03:35 UTC, merged