[react-components]: updating the infrastructure components
open-rmf/rmf-web pull request #525
Opened 2021-10-12 05:01 UTC by vallq

fixes #505 #491

## What's new
- Updating the name of the tab
- Components colors are updated to match the latest figma prototype
- Each cell is sized to the smallest occupiable space given its contents
- Scrolling within each panel to accommodate a large number of cells

![Screenshot 2021-10-12 at 11-54-20 RMF Dashboard](https://user-images.githubusercontent.com/28668944/136889144-f772df27-b870-45ed-b487-58cd78e5ed3c.png)
![Screenshot 2021-10-12 at 11-52-19 RMF Dashboard](https://user-images.githubusercontent.com/28668944/136889150-632871a9-f296-4405-8dd4-6e92bd84bcb9.png)

## Self-checks

- [x] I have prototyped this new feature (if necessary) on Figma 
- [x] I'm familiar with and follow this [Typescript guideline](https://basarat.gitbook.io/typescript/styleguide)
- [ ] I added unit-tests for new components
- [ ] I tried testing edge cases
- [ ] I tested the behavior of the components that interact with the backend, with an e2e test

## Discussion
![final_61650a0c850fb200b1dddbae_832634](https://user-images.githubusercontent.com/28668944/136893534-dbc46a62-faaa-4a1f-8680-ed1ccf70ad84.gif)
I'm slightly bothered by the different sizes of the cells in the clinic example and that is due to the different lengths of the door names, but truncating the words does not seem like a good idea? allowing the words to wrap to the next line will cause more deviation in the alignment of the cells. would appreciate any suggestions or comments on this!

2021-10-15 02:44 UTC, vallq commented
- updated with native browser tooltip

2021-10-19 01:46 UTC, koonpeng requested changes

2021-10-19 01:46 UTC, koonpeng commented on packages/react-components/lib/doors/door-panel.tsx
> +    padding: '0 0.2rem',
use `theme.spacing` instead?

2021-10-19 01:46 UTC, koonpeng commented on packages/react-components/lib/doors/door-panel.tsx
> +    overflowY: 'scroll',
use `auto` to hide scrollbar when it is not needed?

2021-10-19 01:46 UTC, koonpeng commented on packages/react-components/lib/doors/door-panel.tsx
> +    backgroundColor: theme.palette.common.white,
use theme colors to avoid bugs

![image](https://user-images.githubusercontent.com/45189696/137828800-35f36108-b289-496e-88e4-17f67b4d8602.png)

2021-10-19 01:46 UTC, koonpeng commented on packages/react-components/lib/doors/door-panel.tsx
> +    border: '1px solid #ffffff',
use theme colors

2021-10-19 01:46 UTC, koonpeng commented on packages/react-components/lib/doors/door-panel.tsx
> +    boxShadow: '0px 4px 4px 0px #00000040',
use theme shadows

2021-10-19 01:46 UTC, koonpeng commented on packages/react-components/lib/doors/door-panel.tsx
> +    borderRadius: '8px',
use theme border radius

2021-10-19 01:46 UTC, koonpeng commented on packages/react-components/lib/lifts/lift-panel.tsx
> +    overflowY: 'scroll',
same comments as door-panels.tsx

2021-10-19 01:46 UTC, koonpeng commented on packages/react-components/lib/workcells/workcell-panel.tsx
> +    overflowY: 'scroll',
same comments as door-panel.tsx

2021-10-19 01:46 UTC, koonpeng commented on packages/react-components/lib/workcells/workcell-table.tsx
> +import {
![image](https://user-images.githubusercontent.com/45189696/137829977-c3dc3511-51b3-4be7-8c79-023f7f21c739.png)

I think it looks better if the dispensers and ingestors table columns are aligned.

2021-10-19 01:51 UTC, koonpeng commented
![image](https://user-images.githubusercontent.com/45189696/137830532-21bd5549-1214-48e8-9cc7-3a5372b9aa1a.png)

Is it better if we use the light variant of the colors?

2021-10-19 07:15 UTC, vallq commented
`getContrastText()` right? yes this can be used for the labels

but this will change with the new run of theme colors as well, I think it would be better if the contrastText for the colors match the theme? like dark mode would be white text on a background color and light mode would be black text on a background color

2021-10-22 01:39 UTC, koonpeng requested changes
I think the text on the error labels are hard to read, try using `constrastText` on the text or experiment with using variants of the colors.

2021-10-22 01:39 UTC, koonpeng commented on packages/react-components/lib/doors/door-panel.tsx
>      padding: '1rem',
use theme spacing

2021-10-22 01:39 UTC, koonpeng commented on packages/react-components/lib/doors/door-panel.tsx
>      padding: '0.5rem',
use theme spacing

2021-10-22 01:39 UTC, koonpeng commented on packages/react-components/lib/doors/door-panel.tsx
> +    margin: '0.25rem',
use theme spacing

2021-10-22 01:39 UTC, koonpeng commented on packages/react-components/lib/lifts/lift-panel.tsx
>      padding: '0.5rem',
use theme spacing

2021-10-22 01:39 UTC, koonpeng commented on packages/react-components/lib/lifts/lift-panel.tsx
> +    margin: '0.25rem',
use theme spacing

2021-10-22 04:45 UTC, koonpeng commented
That looks ok to me, not sure why my build doesn't reflect the changes :thinking:. I have no opinion on whether if changing the color variants would make better ui.

2021-11-12 10:52 UTC, vallq commented
integrated the virtualized scrolling changes and aligned the table headers for the workcell table!

2021-11-16 02:23 UTC, vallq commented
okay! do you wanna add it in or I'll reference the other pr and make the changes?

2021-11-16 02:48 UTC, ChawinTan commented
I will create a separate pr to merge in again once the changes are more or less approved in the robot tab.

2021-11-25 06:21 UTC, ChawinTan approved these changes
I approve the changes but will hold back on merging first once the map zooming changes has been reviewed and approved on the robot tab. The existing prs seemed to be different enough that the order or merging should not be an issue.

2021-11-29 03:17 UTC, aaronchongth commented
Per VC, this should wait for https://github.com/open-rmf/rmf-web/pull/530 to be merged.

2021-12-03 01:41 UTC, koonpeng approved these changes

2021-12-03 14:30 UTC, merged