Justified left and working ExpandableIssue
open-rmf/rmf-web pull request #602
Opened 2022-04-18 09:19 UTC by aaronchongth

Signed-off-by: Aaron Chong <aaronchongth@gmail.com>

## What's new

Basic grid-based list of issues where the category is shown, and after expanding the details of the issue is shown.

### Quick and dirty test

This can be tested by spoofing some issues in https://github.com/open-rmf/rmf_ros2/blob/main/rmf_fleet_adapter/src/rmf_fleet_adapter/agv/FleetUpdateHandle.cpp#L853-L859 from the original to
```
// for (const auto& issue : issues)
      for (int i = 0; i < 3; ++i)
      {
        nlohmann::json issue_msg;
        // issue_msg["category"] = issue->category;
        // issue_msg["detail"] = issue->detail;
        issue_msg["category"] = "fake_category";
        std::stringstream ss;
        ss << i;
        issue_msg["detail"] = ss.str();
        issues_msg.push_back(std::move(issue_msg));
      }
```

```
cd ~/ws
rm -rf install/rmf_fleet_adapter build/rmf_fleet_adapter
colcon build --packages-select rmf_fleet_adapter

source install/setup.bash
ros2 launch rmf_demos_gz office.launch.xml server_uri:="ws://localhost:8001"
```

![image](https://user-images.githubusercontent.com/5383623/163787146-d1c037eb-0242-430f-8aca-1fc6f6677fda.png)

2022-04-18 10:08 UTC, mayman99 commented
I get an exception when I click on a robot `Cannot read properties of null (reading 'map')`
the compiled line is
`                React.createElement(List, { dense: true, disablePadding: true, component: "div", role: "list" },
`

2022-04-18 10:09 UTC, mayman99 requested changes
breaks when i click on a robot

2022-04-18 14:45 UTC, aaronchongth commented
Hmm, I can't seem to get that exception though,

https://user-images.githubusercontent.com/5383623/163825227-7e0b75a3-6a6d-41b5-a0cc-8ba96a49e388.mp4

do you have a screen recording of it happening?

2022-04-19 06:18 UTC, mayman99 commented
![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/10261903/163938460-ff0484bd-4821-4810-b52e-c5f375604283.gif)

2022-04-19 06:20 UTC, mayman99 commented
maybe i miss merged sth? could you try pulling and telling me if it still works for you?
because if thats the case then it could be because of my outdated backend.

2022-04-21 10:54 UTC, closed without merging