dashboard: Add sort by date to tasks table
open-rmf/rmf-web pull request #637
Opened 2022-09-05 22:34 UTC by quiquequique

## What's new
This PR adds a basic sort by date feature to the tasks task table in the UI. <br>
The changes affect only the react app leaving the FastAPi as it was till now.<br>
![sortTasksByDate](https://user-images.githubusercontent.com/61993763/188517685-73a1d5cf-fdbd-4a93-bfb1-985acc4ee668.gif)

## Self-checks

- [ ] I have prototyped this new feature (if necessary) on Figma 
- [ ] I'm familiar with and follow this [Typescript guideline](https://basarat.gitbook.io/typescript/styleguide)
- [ ] I added unit-tests for new components
- [ ] I tried testing edge cases
- [ ] I tested the behavior of the components that interact with the backend, with an e2e test

## Discussion

2022-09-06 17:27 UTC, aaronchongth requested changes
I have some minor comments that we spoke about yesterday, while waiting for @akash-roboticist's review too.

2022-09-06 20:38 UTC, quiquequique commented on packages/react-components/lib/tasks/task-table.tsx
> +  Button,
addressed

2022-09-06 20:39 UTC, quiquequique commented on packages/react-components/lib/tasks/task-table.tsx
> +              Date
addressed in separated PR

2022-09-07 05:02 UTC, aaronchongth commented
I will close this in favor of https://github.com/open-rmf/rmf-web/pull/638

2022-09-07 05:02 UTC, closed without merging