Favorite tasks
open-rmf/rmf-web pull request #676
Opened 2023-02-13 20:36 UTC by Angatupyry

## What's new
Favorite tasks are added. 

- The user will be able to create favorite tasks for those he/she considers recurrent.

- The user will be able to edit his/her favorite tasks. 

- The user will be able to delete his/her favorite tasks. 

[chrome-capture-2023-1-13.webm](https://user-images.githubusercontent.com/37310205/218568717-fc308ed7-baf4-46f3-812a-4d18bce12706.webm)

[chrome-capture-2023-1-13 (1).webm](https://user-images.githubusercontent.com/37310205/218568754-d2728195-c134-469e-9479-35ab3f809a9b.webm)

[chrome-capture-2023-1-13 (2).webm](https://user-images.githubusercontent.com/37310205/218568773-045d1e89-c30f-4e86-9c48-2ad2dfbdb0d7.webm)

[chrome-capture-2023-1-13 (3).webm](https://user-images.githubusercontent.com/37310205/218568794-206951c2-ab36-4fc2-9c28-8ff19623348e.webm)

## Self-checks

- [ ] I have prototyped this new feature (if necessary) on Figma 
- [ ] I'm familiar with and follow this [Typescript guideline](https://basarat.gitbook.io/typescript/styleguide)
- [ ] I added unit-tests for new components
- [ ] I tried testing edge cases
- [ ] I tested the behavior of the components that interact with the backend, with an e2e test

## Discussion

2023-02-16 07:15 UTC, aaronchongth requested changes
Thanks for the awesome work, @Angatupyry! This is freaking amazing!

Going back to the issue regarding running on the default sqlite database mentioned in VC, I believe I found the issue, which is that we are not indexing the `user` attribute (which is a `JSONField` and not index-able), I've made some quick suggestions below to change the user field to `CharField` and use `self.user.username` instead of the full json, https://github.com/open-rmf/rmf-web/blob/main/packages/api-server/api_server/models/tortoise_models/user.py#L11. This is under the assumption that all usernames are unique. Some quick testing, the favorite tasks started showing up :partying_face: 

Clicking on the saved favorite task, so far does not populate the create-task-dialog properly for me. If I saved a Delivery task, it correctly populates the task type, but the fields stay empty, similar to the Loop task. This could be due to the changes to `user` field on my end, once those changes have been incorporated, you might see the same issue too. Could you help look into that as well?

2023-02-16 15:54 UTC, Angatupyry commented on packages/dashboard/src/components/tasks/tasks-app.tsx
> +                showAlert('success', 'Successfully');
If the user is creating a favorite task the message will be "Created favorite task successfully", if he/she is deleting the message will be "Deleted favorite task successfully" and if he/she is editing the message will be "Edited favorite task successfully"

2023-02-16 16:06 UTC, Angatupyry commented on packages/dashboard/src/components/tasks/tasks-app.tsx
> +              deleteFavoriteTask={deleteFavoriteTask}
Done! Please take a look!

2023-02-23 08:02 UTC, aaronchongth requested changes
Thanks for the quick iteration, it works great! I've left a few nitpicks here and there but the overall feature is working well.

It just occurred to me that there is an important component of Open-RMF that I may not have briefed you about before, which is [rmf_api_msgs](https://github.com/open-rmf/rmf_api_msgs), the models in `api-server/api_server/models/rmf_api` are generated from the json schemas listed in that repository, using this script, https://github.com/open-rmf/rmf-web/blob/main/packages/api-server/generate-models.sh

I would suggest opening a PR on that repository to add the new json schemas for favorite tasks, generate it, and committing those generated models here, as well as updated the commit hash in the generation script. This will ensure compatibility upstream, and that the models we are using, can truly be written in json schema form.

2023-02-23 14:55 UTC, Angatupyry commented on packages/react-components/lib/tasks/create-task.tsx
> +    if (!validateFavoriteTitle()) {
I agree with you!

2023-02-23 14:57 UTC, Angatupyry commented on packages/react-components/lib/tasks/create-task.tsx
> +  const [favoriteTask, setFavoriteTask] = React.useState<TaskFavorite>(defaultFavoriteTask());
Yeah!
Make sense! I will change it.

2023-02-23 15:38 UTC, Angatupyry commented on packages/react-components/lib/tasks/create-task.tsx
> +      setSaving(true);
Both are required to momentarily disable the submit button [here](https://github.com/open-rmf/rmf-web/blob/main/packages/react-components/lib/confirmation-dialog.tsx#L74). 
If we merge `setSaving(setSavingFavoriteTask)` and `setDeleting(setDeletingFavoriteTask)` into a single state then that functionality would not be available for the submit button when a user saves a favorite task and then automatically tries to delete some favorite task.

2023-02-24 04:07 UTC, aaronchongth commented on packages/react-components/lib/tasks/create-task.tsx
> +      setSaving(true);
Oh sorry I don't mean that, I meant changing
```
setSaving(true);
try {
  setSaving(true);
```
to
```
set Saving(true);
try {
  ...
```

2023-02-24 17:41 UTC, Angatupyry commented on packages/api-server/api_server/routes/tasks/tasks.py
> +async def post_favorite_task(
Yeah!
I added some tests.

2023-02-24 17:47 UTC, Angatupyry commented on packages/react-components/lib/tasks/create-task.tsx
> +      setSaving(true);
Oh, man. I catch it now. Sorry. 
Definitely it is not necessary. Good point. 
Thanks for your review.

2023-03-03 05:11 UTC, aaronchongth requested changes
Everything looks good! Just that tiny nitpick regarding import order and we're good to go!

2023-03-03 05:11 UTC, aaronchongth commented on packages/react-components/lib/tasks/create-task.tsx
> +  ListItemSecondaryAction,
nit: could you help sort this in alphabetical order?

2023-03-03 05:13 UTC, aaronchongth commented
Per VC, we will be merging this into `deploy/hammer`, to be backported into `main` after https://github.com/open-rmf/rmf_api_msgs/pull/33 and all other API changes for this project has been merged. This will help us reduce the number of PRs for generation of API messages for the API server, and allow us to fix any incoming broken behaviors once the API is updated.

2023-03-05 07:40 UTC, aaronchongth approved these changes
thanks! LGTM!

2023-03-05 07:42 UTC, aaronchongth commented
I noticed that there was a bunch of commits that were not signed earlier in this PR, I don't think it is a big deal, but let's make sure each commit is properly signed with gpg next time. Thanks!

2023-03-05 07:42 UTC, merged