Fix task_favorite model
open-rmf/rmf-web pull request #686
Opened 2023-03-06 19:24 UTC by Angatupyry

Set name, description, and category fields as required.

2023-03-10 03:52 UTC, aaronchongth requested changes
Thanks for getting back so quickly! I've only just noticed that our routes are `tasks/favorite_task`, I think it would be better if we kept the routes separate from `tasks`, I like the separation of concern that KP implemented for the scheduling backend, https://github.com/open-rmf/rmf-web/pull/672/files#diff-49343ae99efda11415c743d6fc2ccf51977e8ece61cb8a179369ccfc09de6fa5R92, using a prefix

So along with this refactor, perhaps we should have favorite tasks be it's own file under `routes/tasks/favorite_tasks.py`, and have its own route `/favorite_tasks`, this will help us a ton down the road when we need to iterate or test more

this is looking great! once this gets merged we can cherry pick this and https://github.com/open-rmf/rmf-web/pull/676 back into `main`

2023-03-10 13:47 UTC, Angatupyry commented
> Thanks for getting back so quickly! I've only just noticed that our routes are `tasks/favorite_task`, I think it would be better if we kept the routes separate from `tasks`, I like the separation of concern that KP implemented for the scheduling backend, https://github.com/open-rmf/rmf-web/pull/672/files#diff-49343ae99efda11415c743d6fc2ccf51977e8ece61cb8a179369ccfc09de6fa5R92, using a prefix
> 
> So along with this refactor, perhaps we should have favorite tasks be it's own file under `routes/tasks/favorite_tasks.py`, and have its own route `/favorite_tasks`, this will help us a ton down the road when we need to iterate or test more
> 
> this is looking great! once this gets merged we can cherry pick this and #676 back into `main`

Done!
Thanks for the quick review!

2023-03-13 02:45 UTC, aaronchongth requested changes
Looks great! I think I may have found some stale unused code, let me know if it is used anywhere. But otherwise, LGTM!

2023-03-13 02:45 UTC, aaronchongth commented on packages/api-server/api_server/repositories/tasks.py
> +    unix_millis_earliest_start_time: int
Are these being models being used somewhere? I can't seem to find any references to them

2023-03-13 14:52 UTC, aaronchongth approved these changes
Thanks! LGTM!

2023-03-13 14:52 UTC, merged