Delete the entire recurring event or only the selected event
open-rmf/rmf-web pull request #742
Opened 2023-08-22 20:29 UTC by Angatupyry

## What's new

- New field added into ScheduleTask model. `except_dates`. An array that stores the dates that the user does not want a job to run. 
- Added an endpoint to regenerate the schedule based on exception days. 
- Added a pop-up with the option to delete all events or just the selected event. 

[chrome-capture-2023-7-22.webm](https://github.com/open-rmf/rmf-web/assets/37310205/878a158f-a35f-43a8-9394-a292ab16a101)

[chrome-capture-2023-7-22 (1).webm](https://github.com/open-rmf/rmf-web/assets/37310205/8901584e-9d3d-4190-8d31-f8076e251f35)

## Self-checks

- [ ] I have prototyped this new feature (if necessary) on Figma 
- [ ] I'm familiar with and follow this [Typescript guideline](https://basarat.gitbook.io/typescript/styleguide)
- [ ] I added unit-tests for new components
- [ ] I tried testing edge cases
- [ ] I tested the behavior of the components that interact with the backend, with an e2e test

## Discussion

2023-08-24 04:05 UTC, aaronchongth requested changes
Thanks for handling this epic feature! I'll test the feature over the weekend for multiple days to check that scheduling and deletion is working. For now, I've left some comments, let me know what you think!

2023-08-24 16:08 UTC, Angatupyry commented on packages/dashboard/src/components/tasks/tasks-app.tsx
> +  Radio,
I thought our precommit did it automatically. I will keep this in mind for future implementations
Thanks for catching it!
Done cb9f5bfe37cc43cc3a59bd98b3538da5bebdecb3 !

2023-08-24 19:20 UTC, Angatupyry commented on packages/dashboard/src/components/tasks/tasks-app.tsx
> +            console.log(exceptDateRef.current);
Done b96ccfea44190891c5c936eafe60c1a29a1aa30f !

2023-08-24 19:29 UTC, Angatupyry commented on packages/dashboard/src/components/tasks/tasks-app.tsx
> +          return;
Sure thing!
I used `throw` in order to capture the error and return it in the catch statement 
c8c43e395caae7ccc858008b7663d30914b2cc62

2023-08-24 19:39 UTC, Angatupyry commented on packages/api-server/api_server/routes/tasks/scheduled_tasks.py
> +async def regenerate_schedule_by_except_date(
Yeah. Makes sense!
11099e641c38858c1364e96abd00c9502c74c73d

2023-08-24 19:39 UTC, Angatupyry commented on packages/api-server/api_server/routes/tasks/scheduled_tasks.py
> +    except_date: datetime,
11099e641c38858c1364e96abd00c9502c74c73d

2023-08-25 07:35 UTC, aaronchongth approved these changes
Awesome stuff! Thanks! LGTM

2023-08-25 07:35 UTC, merged