support jazzy
open-rmf/rmf-web pull request #955
Opened 2024-06-12 05:41 UTC by koonpeng

## What's new

Update to nobel+jazzy.

## Self-checks

- [ ] I have prototyped this new feature (if necessary) on Figma 
- [ ] I'm familiar with and follow this [Typescript guideline](https://basarat.gitbook.io/typescript/styleguide)
- [ ] I added unit-tests for new components
- [ ] I tried testing edge cases
- [ ] I tested the behavior of the components that interact with the backend, with an e2e test

## Discussion

2024-06-26 05:40 UTC, aaronchongth approved these changes

2024-06-26 05:59 UTC, aaronchongth requested changes
While running simulation tests, I noticed that
* the simulation is already running, then only we start the api-server, it will segfault
* after starting the api-server, then starting the simulation, the segfault occurs when a task is dispatched

2024-06-26 07:53 UTC, koonpeng commented
By segfault, you mean that rmf crashes? Let me see if I can reproduce it.

2024-06-26 08:23 UTC, koonpeng commented
Not able to reproduce it, though I get a different error

```
[fleet_adapter-14] Other error for tinyRobot2 in get_data: 'robot_name'
```

2024-06-27 02:27 UTC, aaronchongth commented
Sorry that was cryptic of me, I mean't api-server crashes. Let me attach some screenshots

![image](https://github.com/open-rmf/rmf-web/assets/5383623/ea30038a-b256-490c-885f-50438d820b5d)

As for the different error, it looks like you may have an outdated workspace, I remember seeing this error before I rebuilt off `main` for everything

2024-06-27 03:14 UTC, koonpeng commented
I'm not able to reproduce it, I can run with sim and managed to send a task.

2024-07-01 02:39 UTC, aaronchongth approved these changes
Thanks for supporting this! LGTM

Looks like our migration effort of deployment branches have more to keep up with!

2024-07-01 02:40 UTC, merged